{{#with cfg.sparc}}
production:
  default_mail_to: "{{default_mail_to}}"
  admin_mail_to: "{{admin_mail_to}}"
  contact_us_mail_to: "{{contact_us_mail_to}}"
  feedback_mail_to: "{{feedback_mail_to}}"
  use_feedback_link: {{use_feedback_link}}
  new_user_cc: "{{new_user_cc}}"
  system_satisfaction_survey_cc: "{{system_satisfaction_survey_cc}}"
  root_url: {{protocol}}://{{host}}
  user_portal_link: {{protocol}}://{{host}}/portal/
  dashboard_link: {{protocol}}://{{host}}/dashboard
  header_link_1: {{header_link_1}}
  header_link_2: {{header_link_2}}
  header_link_3: {{header_link_3}}
  use_indirect_cost: {{use_indirect_cost}}
  use_shiboleth: {{use_shiboleth}}
  use_shibboleth_only: {{use_shibboleth_only}}
  use_ldap: {{use_ldap}}
  suppress_ldap_for_user_search: {{suppress_ldap_for_user_search}}
  wkhtmltopdf_location: "{{wkhtmltopdf_location}}"
  approve_epic_rights_mail_to: "{{approve_epic_rights_mail_to}}"
  use_epic: {{use_epic}}
  queue_epic: {{queue_epic}}
  queue_epic_load_error_to: "{{queue_epic_load_error_to}}"
  use_google_calendar: {{use_google_calendar}}
  use_news_feed: {{use_news_feed}}
  google_username: {{google_username}}
  google_password: {{google_password}}
  send_authorized_user_emails: {{send_authorized_user_emails}}
  system_satisfaction_survey: {{system_satisfaction_survey}}
  no_reply_from: "{{no_reply_from}}"
  # new for v1.4.0 ...

  editable_statuses:
{{#each editable_statuses as |key value|}}
    {{key}}:
  {{#each value as |status|}}
      - {{value}}
  {{/each}}
{{/each}}

  updatable_statuses:
{{#each updatable_statuses as |status|}}
    - {{status}}
{{/each}}

  navbar_links:
    sparc_request:
      - SPARCRequest
      - {{protocol}}://{{host}}
    sparc_dashboard:
      - Dashboard
      - {{protocol}}://{{host}}/dashboard
    sparc_catalog:
      - SPARCCatalog
      - {{protocol}}://{{host}}/catalog_manager
    sparc_report:
      - SPARCReport
      - {{protocol}}://{{host}}/reports

{{#each navbar_links as |value key|}}
    {{key}}:
  {{#each value as |status|}}
      - {{value}}
  {{/each}}
{{/each}}

  # API
  remote_service_notifier_protocol: "{{remote_service_notifier_protocol}}"
  remote_service_notifier_host: "{{remote_service_notifier_host}}"
  remote_service_notifier_path: "{{remote_service_notifier_path}}"
  remote_service_notifier_username: "{{remote_service_notifier_username}}"
  remote_service_notifier_password: "{{remote_service_notifier_password}}"
  host: "{{host}}"
  current_api_version: "{{current_api_version}}"
  clinical_work_fulfillment_url: {{clinical_work_fulfillment_url}}
  # end API
  #
  # allow catalog_manager to turn on fulfillment one organization at a time
  fulfillment_contingent_on_catalog_manager: {{fulfillment_contingent_on_catalog_manager}}
  send_emails_to_real_users: {{send_emails_to_real_users}}
{{/with}}
